### ISSUE TITLE
submit the parenthesis checker program using stack

### ISSUE THREAD

**Issue by ManasDroid** [ManasDroid/Hacktoberfest2020#13]
add to data structures

**Comment by varunvjha** [comment]
I want to work on this in Java

**Comment by Rj-coder-iitian** [comment]
I want to work on this in C language.

**Comment by sravanireddy1102** [comment]
Can I work on this using python language

**Comment by rajanshoo25** [comment]
Can I work on this in C++

**Comment by trallnag** [comment]
use weapon of Java to defeat bug

**Comment by ManasDroid** [comment]
u can use whichever language you want

**Comment by sahirmpatel** [comment]
> use weapon of Java to defeat bug

kek
