### ISSUE TITLE
create a basic calculator

### ISSUE THREAD

**Issue by manish2202** [ManasDroid/Hacktoberfest2020#33]
I want to create a C program on basic calculator.

**Comment by Akshat511716** [comment]
Can you explain what are the functionalities to be included in this calculator program?

**Comment by manish2202** [comment]
I will add sqrt and other operations also. I need this urgently.

**Comment by ManasDroid** [comment]
lgtm go ahead @manish2202 !

**Comment by manish2202** [comment]
thanks. working on it.

**Comment by shweta-laha** [comment]
hey! I want to contribute in your project.
