### ISSUE TITLE
Reverse a string using stack

### ISSUE THREAD

**Issue by ManasDroid** [ManasDroid/Hacktoberfest2020#4]
Add in Data structures folder.

**Comment by soumy47** [comment]
Hey,I wanna work on this issue.

**Comment by ANKITAKHAN** [comment]
@ManasDroid I want to contribute to this issue.

**Comment by ManasDroid** [comment]
@ANKITAKHAN go ahead !

**Comment by aayushi02agarwal** [comment]
Wanna do it in cpp!
