### ISSUE TITLE
Add sorting programs.

### ISSUE THREAD

**Issue by ManasDroid** [ManasDroid/Hacktoberfest2020#45]
Create a new folder named "Sorting"& inside that add sorting programs of atleast 5 different types.

**Comment by T3KRAJ** [comment]
Love to contribute to this issue.

**Comment by rohan8660** [comment]
I want to do this. Should I wait to assign or create a PR right away ?

**Comment by mk1107** [comment]
I can contribute in this. Please allow me to do so.
